$twitter = read csv from 'file:///home/fabian/Desktop/twitter_1000k.csv' columns ['k', 'fk'] delimiter ',';

$output = join $twitter1 in $twitter, $twitter2 in $twitter, $twitter3 in $twitter where
	($twitter1.fk == $twitter2.k
	and $twitter2.fk == $twitter3.k
	and $twitter3.fk == $twitter1.k)
	into sort([$twitter1.k, $twitter2.k, $twitter3.k]) parallel 8;
	
write $output to 'file:///home/fabian/Desktop/twitter_result.csv' columns ['k', 'fk'] delimiter ',';